@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AssignCommandParser" as AssignCommandParser LOGIC_COLOR
participant "a:AssignCommand" as AssignCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("assign 2 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("assign 2 1")
activate AddressBookParser

create AssignCommandParser
AddressBookParser -> AssignCommandParser
activate AssignCommandParser

AssignCommandParser --> AddressBookParser
deactivate AssignCommandParser

AddressBookParser -> AssignCommandParser : parse("2 1")
activate AssignCommandParser

create AssignCommand
AssignCommandParser -> AssignCommand
activate AssignCommand

AssignCommand --> AssignCommandParser
deactivate AssignCommand

AssignCommandParser --> AddressBookParser : a
deactivate AssignCommandParser
AssignCommandParser -[hidden]-> AddressBookParser
destroy AssignCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AssignCommand : execute(m)
activate AssignCommand

AssignCommand -> Model : assignNurseToPatient(2,1)
activate Model

Model --> AssignCommand
deactivate Model

create CommandResult
AssignCommand -> CommandResult
activate CommandResult

CommandResult --> AssignCommand
deactivate CommandResult

AssignCommand --> LogicManager : r
deactivate AssignCommand

[<--LogicManager
deactivate LogicManager
@enduml
