@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class Bloodtype
Class Appointment
Class NextOfKin
Class Checkup
Class MedicalHistory
Class DateOfBirth
Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
Person *-left-> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *-right-> "*" Tag
Person *--> Bloodtype
Person *--> Appointment
Person *-down-> NextOfKin
Person *--> "*" MedicalHistory
Person *--> "*" Checkup
Person *-left-> DateOfBirth

I -[hidden]up--> UserPrefs
Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

Name -[hidden]down-> Phone
Name -[hidden]down-> NextOfKin
Tag -[hidden]down-> MedicalHistory
Tag -[hidden]down-> Bloodtype

Phone -[hidden]down-> Email
Phone -[hidden]right-> NextOfKin
NextOfKin -[hidden]down->DateOfBirth
NextOfKin -[hidden]right-> Address
NextOfKin -[hidden]down->Email

Address -[hidden]down-> Appointment
Address -[hidden]right->Bloodtype
Address -[hidden]down->DateOfBirth
Bloodtype -[hidden]down-> Checkup
Bloodtype -[hidden]down-> Appointment
Bloodtype -[hidden]right-> MedicalHistory
MedicalHistory -[hidden]down->Checkup


DateOfBirth -[hidden]up-> Address
DateOfBirth -[hidden]up->NextOfKin
Appointment -[hidden]up-> Bloodtype
Checkup -[hidden]up->Bloodtype

ModelManager --> "~* filtered" Person
'ModelManager --> "~* sorted" Person
@enduml
